"""Regenerate the integer angle tables used by the ST010 command model."""

import math
from pathlib import Path


def render_table(name, cpp_type, values, columns):
    rows = [", ".join(str(v) for v in values[i : i + columns])
            for i in range(0, len(values), columns)]
    return (f"inline constexpr std::array<{cpp_type}, {len(values)}> {name}{{\n"
            + "\n".join(f"    {row}," for row in rows) + "\n};\n")


sine = [math.floor(32767 * math.sin(2 * math.pi * i / 256) + 0.5)
        for i in range(256)]
# Preserve the command model's one-count departures from a rounded sine curve.
for i in (120, 131, 147, 163):
    sine[i] -= 1
for i in (206, 227, 231, 234, 238, 239, 241, 244, 246, 248, 252, 254):
    sine[i] += 1
arc = [int(math.atan2(x, y) * 128 / math.pi + 0.5) if x else 0
       for x in range(32) for y in range(32)]
arc[10 * 32 + 9] -= 2
arc[31 * 32 + 8] -= 1

output = Path(__file__).resolve().parents[1] / "core/src/cartridge/St010Tables.hpp"
output.write_text(
    "// Generated by tools/generate_st010_tables.py.\n#pragma once\n\n"
    "#include <array>\n#include <cstdint>\n\nnamespace snes::core::st010 {\n\n"
    + render_table("Sine", "int16_t", sine, 8) + "\n"
    + render_table("Arc", "uint8_t", arc, 32)
    + "\n} // namespace snes::core::st010\n", encoding="utf-8")
